<font color="teal" size=10> Inputs and outputs</font>

In [4]:
# To basic to note...we know this stuff
sum([1,2,3])
var = [2,4,5]
sum(var)/len(var) # calc the mean

3.6666666666666665

<font color="teal" size=11>Numpy</font>

In [5]:
import numpy as np
numbers = [1,2,3,4]
np.mean(numbers)

np.float64(2.5)

In [7]:
np.linspace(1,7,7)

array([1., 2., 3., 4., 5., 6., 7.])

In [10]:
x = np.linspace(1,5,3)
type(x) # numpy ndarray; aka numpy array nd for n-dimensional; numpy allows us to create multi-dimensional arrays

print(type(numbers))
numbers_np = np.array(numbers) # convert list to nump array
print(type(numbers_np))

np.max(numbers) # even though it's not a numpy array, it's a list, it still works

<class 'list'>
<class 'numpy.ndarray'>

np.int64(4)

In [14]:
# if u just neeeded the mean function and not having to reference np.mean(), we can do
# this has the addede benfit of not importing the entire numpy library
from numpy import mean as m 

m([1,2,3])

np.float64(2.0)

In [22]:
# in-place vs non-inplace
n = [3,2,4,1,33]
n.sort()
print(n)
nparr = np.array(n)
nparr.sort() # running sort()) as a method
print(nparr)
np2 = np.array([8,2,7])
print(np2)
np.sort(np2)
print(np2,np.sort(np2))  # running numpy.sort() is not inplace

[1, 2, 3, 4, 33]
[ 1  2  3  4 33]
[8 2 7]
[8 2 7] [2 7 8]

<font color="teal" size=10>Pandas</font>

Used for spreadsheet (2d) type of data orginzation. Comes up often in ML but not so much in DL (because we have higher dimensions).

In [37]:
import numpy as np
import pandas as pd 

# create random data
# returns a random number from a Gaussian distribution i.e. normal distribution. that is what the 'n' in randn is for
np.random.randn() 
# normal dist has a mean of 0 and standard deviation of 1
np.random.randn(5,5)
np.random.randn(5,5)*5 + 20
var1 = np.random.randn(100)*5 + 20
var2 = np.random.randn(100) > 0

# variable labels
labels = ['Temp (C)','Ice Cream']
# create a dictionary to put them together
D = {labels[0]:var1,labels[1]:var2}
#D
# Import the dictionary into a pandas dataframe

df = pd.DataFrame(data=D)
type(df)
df

(     Temp (C)  Ice Cream
 0    9.114551       True
 1   22.993969       True
 2   20.177118       True
 3   33.240883      False
 4   19.193885       True
 ..        ...        ...
 95  15.553123      False
 96  14.359138      False
 97  16.136438       True
 98  18.525673      False
 99  24.431145       True

 [100 rows x 2 columns],
     Temp (C)  Ice Cream
 0   9.114551       True
 1  22.993969       True
 2  20.177118       True
 3  33.240883      False
 4  19.193885       True,
 Temp (C)     100
 Ice Cream    100
 dtype: int64)

In [38]:
df.head()

    Temp (C)  Ice Cream
0   9.114551       True
1  22.993969       True
2  20.177118       True
3  33.240883      False
4  19.193885       True

In [39]:
df.count()

Temp (C)     100
Ice Cream    100
dtype: int64

In [42]:
 # note ice cream is boolean but pandas knows to convert them to 0 and 1 and the mean is around .5
# meaning 1/2 the labels are false and half are true
df.mean()

Temp (C)     19.828081
Ice Cream     0.480000
dtype: float64

In [79]:
# Exercise 
# Create a pandas data from with:
# integers going from 0 to 10, their square, and their log. So 10 rows and 3 cols


nums = np.array(range(11))
df = pd.DataFrame({'row':nums,'squared':nums**2,'log':np.log(nums)})
df

C:\Users\mpere\AppData\Local\Temp\ipykernel_17176\1405289107.py:7: RuntimeWarning: divide by zero encountered in log
  df = pd.DataFrame({'row':nums,'squared':nums**2,'log':np.log(nums)})

    row  squared       log
0     0        0      -inf
1     1        1  0.000000
2     2        4  0.693147
3     3        9  1.098612
4     4       16  1.386294
5     5       25  1.609438
6     6       36  1.791759
7     7       49  1.945910
8     8       64  2.079442
9     9       81  2.197225
10   10      100  2.302585

In [85]:
# Help on functions
x = [1,2,3]
sum(x,3) 
# help(sum)
#sum()? or sum()??
#np.linspace?

9

In [ ]:
def awesomeFunc(input1,input2):
    s = input1+input2
    return s

awesomeFunc(1,3)

4

In [91]:
def evenMoreCool(input1,input2):
    prd = input1*input2
    sum = input1+input2
    return sum,prd #<-- note returns a tuple cause of the ','

aTuple = evenMoreCool(1,2)
aTuple
a,b = evenMoreCool(1,2)
print(a)
print(b)

3
2

<font color="orange" size=8px>Lambda Function</font>

- when u need short a function

In [93]:
funname = lambda x: x**2-1
funname(2)

3

In [114]:
# Ex: Create  a fcn that computes a factorial
import math

def myFactorial(n):
    return np.prod(np.arange(1,n+1))

y = 3
myFactorial(y),math.factorial(y)

(np.int64(6), 6)

In [123]:
# Ex: Write a fcn that flips a coin N  times, and reports the mean

import numpy as np

def flip(n):
    res = np.random.randn(n) > 0
    print(res)
    return res
print(np.mean( flip(3) )*100)

[ True  True False]
66.66666666666666

In [ ]:
# Copies and referents
a = [4,3]
b = a
# b refers to a and point to the same memory just w/diff names
print(id(a))
print(id(b))
b[0] = 14 # changes a
a

c = a[:]  # make a copy. works for simple cases not classes etc..need to check your work
c[0] = 33
a

d = {'q':1,'w':2}
# f = d[:] won't work
import copy
## used for copying instancs, matrices,arrays etc... used alot in DL

f = copy.deepcopy(d)
f

2440645668672
2440645668672

{'q': 1, 'w': 2}